### ISSUE TITLE
Segment cleanup timer not working

### ISSUE THREAD

**Issue by miguesan01** [freeconga/Valetudo#69]
## Describe the bug

Timers with segment cleanup isn't working, in the log you can see that the timer is executed but an error is raised up. It only happens with segment cleanup timers , full cleanup timer always works like a charm. I have congatudo latest release installed (2023.03.0, downloaded from github, not compiled by me) in standalone mode.

## To Reproduce

1. Add segment cleanup timer.
2. Wait until the timer's programed time is reached.
3. Robot won't start cleanning, and error is reported in log.

### Screenshots

![photo_4_2023-03-22_11-15-21](https://user-images.githubusercontent.com/87263152/226873655-468395a8-9f4d-43dc-8dff-5f92ca4f9ec0.jpg)
![photo_2_2023-03-22_11-15-21](https://user-images.githubusercontent.com/87263152/226873773-a4cd988a-7c10-485b-860d-743e332ce471.jpg)
![photo_3_2023-03-22_11-15-21](https://user-images.githubusercontent.com/87263152/226873854-fb563d60-6536-4662-998b-9533e9b8e594.jpg)
![photo_1_2023-03-22_11-15-21](https://user-images.githubusercontent.com/87263152/226874003-c128f624-14ae-4beb-af08-c6f0339d31aa.jpg)

### Vacuum Model

Conga 3490
### Congatudo Version

2023.03.0
## Expected behavior

Segment cleanups timers starts cleaninng when rquired.

**Comment by elraro** [comment]
@miguesan01 ¿puedes probar la nueva release 2023.04?

**Comment by miguesan01** [comment]
> @miguesan01 ¿puedes probar la nueva release 2023.04?

Lo siento, no va a poder ser. Compré un nuevo robot de otra marca y este ya no lo tengo, lo regalé.

**Comment by elraro** [comment]
@germanyague alguna novedad?

**Comment by germanyague** [comment]
Still no, with nightly latest:

![Captura de pantalla 2023-05-01 a las 23 36 45](https://user-images.githubusercontent.com/1960405/235536165-6c81f922-d96a-41af-891b-c72662fc2a83.jpg)

2023-05-01T21:36:43.723Z
Warn
ZoneCleaningCapabilityRouter: Error while handling route "/" {
  body: {
    action: 'clean',
    zones: [
      {
        points: {
          pA: { x: 414, y: 411 },
          pB: { x: 444, y: 411 },
          pC: { x: 444, y: 441 },
          pD: { x: 414, y: 441 }
        }
      }
    ],
    iterations: 1
  },
  message: "Cannot read properties of undefined (reading 'map')"
}

**Comment by elraro** [comment]
Solved. Test the nightly release. Please, reopen the issue if you find any problem.
